config/routes.rb
Rails.application.routes.draw do
  
  get '/criminals/find', to: 'criminals#find'
  resources :criminals
  
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/criminal.rb
class Criminal < ApplicationRecord
    self.primary_key = 'ic'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/criminals_controller.rb
class CriminalsController < ApplicationController
    def index
        @criminals = Criminal.all
    end
    
    def show
        @criminal = Criminal.find(params[:id])
    end
    
    def new
        @criminal = Criminal.new
    end
    
    def edit
        @criminal = Criminal.find(params[:id])
    end
    
    def create
        @criminal = Criminal.new(criminal_params)
        
        @criminal.save
        redirect_to @criminal
    end
    
    def destroy
        @criminal = Criminal.find(params[:id])
        @criminal.destroy
        
        redirect_to criminals_path
    end
    
    def find
        @criminal = Criminal.find_by ic: params[:ic]
        if @criminal != nil
            @to_return = {:Status => :Ok, :Message => :"Criminal Found", :Name => @criminal.name, :IC => @criminal.ic, :Offence => @criminal.offence}
            render :json => @to_return
        else
            render :json => {:Status => :Ok, :Message => :'No Criminals Found'}
        end
    end
    
    private
        def criminal_params
            params.require(:criminal).permit(:name, :ic, :offence)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criminals_helper.rb
module CriminalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/criminals/find.html.erb
<h1>Search for Criminal</h1>

<%= form_for :criminal, url: criminals_find_path do |f| %>
  <p>
    <%= f.label :ic %><br>
    <%= f.text_field :ic %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', criminals_path %>

app/views/criminals/index.html.erb
<h1>Criminal DB</h1>


<%= link_to 'New Criminal', new_criminal_path %>

<%= form_tag("/criminals/find", method: "get") do %>
  <br>
  <%= label_tag(:ic, "Enter IC") %>
  <%= text_field_tag(:ic) %><br>
  <%= submit_tag("Search for Criminal") %>
<% end %>

<br>

<table>
  <tr>
    <th>Name</th>
    <th>IC</th>
    <th>Offence</th>
  </tr>
 
  <% @criminals.each do |criminal| %>
    <tr>
      <td><%= criminal.name %></td>
      <td><%= criminal.ic %></td>
      <td><%= criminal.offence %></td>
      <td><%= link_to 'Show', criminal_path(criminal) %></td>
      <td><%= link_to 'Delete', criminal_path(criminal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/criminals/new.html.erb
<h1>New Criminal</h1>

<%= form_for :criminal, url: criminals_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :ic %><br>
    <%= f.text_field :ic %>
  </p>
  
  <p>
    <%= f.label :offence %><br>
    <%= f.text_field :offence %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', criminals_path %>

app/views/criminals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @criminal.name %>
</p>
 
<p>
  <strong>IC:</strong>
  <%= @criminal.ic %>
</p>

<p>
  <strong>Offence:</strong>
  <%= @criminal.offence %>
</p>

<%= link_to 'Back', criminals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriminalsSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Criminal Query System</h1>
<h2>EI Project 2017<h2>
<h3><%= link_to 'To Criminals System', '/criminals' %><h3>